name: Build macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build
          cmake --build build
          otool -L build/SnakeCLI

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: SnakeCLI-macOS
          path: build/SnakeCLI